FROM tensorflow/serving:nightly-devel
RUN mkdir /app
COPY mnist_tensorflow_medium.py /app
COPY mnist_input_data.py /app
COPY mnist_input_data.pyc /app
WORKDIR /app
CMD ["python","mnist_tensorflow_medium.py","/tmp/mnist"]



