apiVersion: v1
kind: Pod
metadata:
  name: mnist-medium-pv
  namespace: bmt-test 
spec:
  restartPolicy: OnFailure
  containers:
    - name: mnist-medium
      image: "docker-registry.default.svc:5000/openshift/mnist-medium:latest"
      volumeMounts:
        - name: mnistpath
          mountPath: /tmp
      securityContext:
       privileged: true
#        seLinuxOptions:
#         level: "s0:c123,c456"
  volumes:
   - name: mnistpath
     hostPath:
      path: /mnist-data
      type: Directory
