apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "core-resource-limits"
spec:
  limits:
  - default:
      cpu: 500m
      memory: 1536Mi
    defaultRequest:
      cpu: 50m
      memory: 512Mi
    max:
      memory: 6Gi
    min:
      memory: 512Mi
    type: Container
  - max:
      memory: 12Gi
    min:
      memory: 512Mi
    type: Pod 
