apiVersion: v1
kind: DeploymentConfig
metadata:
  name: sacp-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: sacp-model-server
    spec:
      securityContext:
       privileged: true
      volumes:
      - name: mnist-light-pv
        persistentVolumeClaim:
         claimName: mnist-light-pvc
      containers:
      - name: sacp-serving-container
        imagePullPolicy: IfNotPresent
        image: tensorflow/serving:latest-devel
        volumeMounts:
        - name: mnist-light-pv
          mountPath: /tmp
        ports:
        - containerPort: 8500
        command:
        - bash
        - -c
        - tensorflow_model_server --port=8500 --rest_api_port=8501 --model_name=mnist --model_base_path=/tmp/mnist-data/mnist;
        restartPolicy: Always
      - name: sacp-rest-container
        image: tensorflow/serving:latest-devel
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: mnist-light-pv
          mountPath: /tmp
        ports:
        - containerPort: 8888
        command:
        - bash
        - -c
        - python /tmp/mnist_client_rest_rpc.py --server=localhost:8500 --concurrency=100
        restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: sacp-service
  name: sacp-service
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: sacp-model-server
  type: ClusterIP
