apiVersion: v1
kind: Pod
metadata:
  name: mnist-light
  namespace: bmt-test 
spec:
  restartPolicy: OnFailure
  containers:
    - name: mnist-light
      image: "docker-registry.default.svc:5000/openshift/mnist-light:latest"
      volumeMounts:
        - name: mnistpath
          mountPath: /tmp/mnist
      env:
        - name: NVIDIA_VISIBLE_DEVICES
          value: all
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: "compute,utility"
        - name: NVIDIA_REQUIRE_CUDA  
          value: "cuda>=5.0"
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        seLinuxOptions:
          type: nvidia_container_t
      resources:
        limits:
          nvidia.com/gpu: 0 # requesting 1 GPU
  volumes:
   - name: mnistpath
     hostPath:
      path: /tmp/
      type: Directory
