apiVersion: v1
kind: Pod
metadata:
  name: mnist-light-pv
spec:
  restartPolicy: OnFailure
  containers:
    - name: mnist-light
      image: "docker-registry.default.svc:5000/openshift/mnist-light:latest"
      volumeMounts:
        - name: mnist-light-pv
          mountPath: /tmp
      securityContext:
       privileged: true    
#        seLinuxOptions:
#         level: "s0:c123,c456"
  volumes:
   - name: mnist-light-pv
     persistentVolumeClaim:
      claimName: mnist-light-pvc
