apiVersion: v1
kind: PersistentVolume
metadata:
  name: mnist-light-pv 
spec:
  capacity:
    storage: 1Gi 
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain 
  nfs: 
    path: /exports/mnist-light
    server: material.bmt.local
    readOnly: false
