# Use an official Python runtime as a parent image

FROM tensorflow/tensorflow:1.14.0-gpu-py3
WORKDIR /app
# Copy the current directory contents into the container at /app
#ADD . /app
COPY mnist_heavy.py /app
COPY requirements.txt /app
# Install any needed packages specified in requirements.txt
RUN echo nameserver 8.8.8.8 > /etc/resolv.conf
RUN apt-get update -y
RUN apt-get install -y python3-pip
RUN pip3 install --upgrade pip
RUN pip3 install --trusted-host pypi.python.org -r requirements.txt
CMD ["python3", "-m", "mnist_heavy"]
