apiVersion: v1
kind: Pod
metadata:
  name: mnist-heavy-pv2
spec:
  affinity:
   nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
     nodeSelectorTerms:
     - matchExpressions:
       - key: openshift.com/gpu-accelerator 
         operator: Exists
  restartPolicy: OnFailure
  containers:
    - name: mnist-heavy
      image: "docker-registry.default.svc:5000/openshift/mnist-heavy:latest"
      env:
        - name: CUDA_VISIBLE_DEVICES
          value: "2"
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: "compute,utility"
      volumeMounts:
        - name: mnistpath
          mountPath: /tmp
      securityContext:
       privileged: true
       capabilities:
         drop: ["ALL"]
       seLinuxOptions:
         type: nvidia_container_t
      resources:
        limits:
          nvidia.com/gpu: 1
#        seLinuxOptions:
#         level: "s0:c123,c456"
  volumes:
   - name: mnistpath
     hostPath:
      path: /mnist-data
      type: Directory
